"""
Scan git repositories for AI co-authored commits and patterns.

Looks for Co-Authored-By indicators, commit message patterns,
and evidence of AI-assisted development workflows.
"""

import subprocess
from pathlib import Path


def scan_repo(repo_path: Path, max_commits: int = 200) -> dict:
    """Scan a git repo for AI collaboration evidence."""
    if not (repo_path / ".git").exists():
        return {"source": "git", "found": False, "error": f"Not a git repo: {repo_path}"}

    try:
        result = subprocess.run(
            ["git", "log", f"--max-count={max_commits}",
             "--format=%H|||%an|||%s|||%b|||%aI"],
            cwd=repo_path, capture_output=True, text=True, timeout=30,
        )
    except (subprocess.TimeoutExpired, FileNotFoundError):
        return {"source": "git", "found": False, "error": "git command failed"}

    if result.returncode != 0:
        return {"source": "git", "found": False, "error": result.stderr.strip()}

    commits = []
    ai_commits = []
    ai_indicators = [
        "co-authored-by: claude",
        "co-authored-by: copilot",
        "co-authored-by: chatgpt",
        "generated by",
        "ai-assisted",
        "ai assisted",
    ]

    for line in result.stdout.strip().split("\n"):
        if not line.strip():
            continue
        parts = line.split("|||")
        if len(parts) < 5:
            continue
        commit = {
            "hash": parts[0][:8],
            "author": parts[1],
            "subject": parts[2],
            "body": parts[3],
            "date": parts[4],
        }
        commits.append(commit)

        full_text = (commit["subject"] + " " + commit["body"]).lower()
        if any(ind in full_text for ind in ai_indicators):
            ai_commits.append(commit)

    return {
        "source": "git",
        "found": True,
        "repo": repo_path.name,
        "total_commits": len(commits),
        "ai_coauthored_commits": len(ai_commits),
        "ai_commits": ai_commits[:50],
        "recent_commits": [
            {"hash": c["hash"], "subject": c["subject"], "date": c["date"]}
            for c in commits[:20]
        ],
    }


def scan_repos(repo_paths: list[Path], max_commits: int = 200) -> list[dict]:
    """Scan multiple repos."""
    return [scan_repo(p, max_commits) for p in repo_paths]
